# Generated by Django 4.1.3 on 2023-01-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phy', '0002_categoryphy_category_name_phy_content_phy_exist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Изображение'),
        ),
    ]
