# Generated by Django 4.1.3 on 2023-02-04 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phy', '0003_alter_phy_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryphy',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterField(
            model_name='categoryphy',
            name='category_name',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Название раздела'),
        ),
        migrations.AlterField(
            model_name='phy',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='phy.categoryphy', verbose_name='Раздел'),
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(null=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='phy.categoryphy', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Формула',
                'verbose_name_plural': 'Формулы',
            },
        ),
    ]
