# Generated by Django 4.1.3 on 2023-02-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phy', '0005_formula_title_alter_formula_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='formula',
            field=models.CharField(max_length=100, null=True, verbose_name='Формула'),
        ),
        migrations.AddField(
            model_name='formula',
            name='lined_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Линейный тип'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
