# Generated by Django 4.1.3 on 2023-02-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phy', '0007_formula_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='image',
        ),
    ]
