# Generated by Django 4.1.3 on 2023-03-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phy', '0009_categoryphy_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='template_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя шаблона'),
        ),
    ]
