# Generated by Django 4.1.3 on 2023-01-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
