# Generated by Django 4.1.3 on 2023-01-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_main_cat_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Главная Страница', 'verbose_name_plural': 'Главная Страница'},
        ),
    ]
