# Generated by Django 4.1.3 on 2023-01-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_main_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='content',
            field=models.TextField(blank=True, default=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='main',
            name='exist',
            field=models.BooleanField(default=True, verbose_name='Существует'),
        ),
        migrations.AddField(
            model_name='main',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Изображение'),
        ),
    ]
