# Generated by Django 4.1.3 on 2023-01-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_main_content_main_exist_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
